### ISSUE TITLE
minimap error using sc_long_pipeline.py

### ISSUE THREAD

**Issue by aheravi** [LuyiTian/FLAMES#13]
Hi @LuyiTian ,
Could you please comment on my error below?

Running code:
```
for i in test; do /FLAMES/python/sc_long_pipeline.py --gff3 hg38v99.Cellranger.genes.gtf --infq $i.demultiplexed.fq.gz --outdir FLAMES_Output/$i --genomefa hg38v99.Cellranger.genome.fa --config_file /FLAMES/config_sclr_nanopore_default.json --minimap2_dir /Software/anaconda_py2/bin/  >$i.log 2>&1 & done
```

Error:
```
Use config file: config_sclr_nanopore_default.json

Parameters in configuration file:

comment : this is the default config for nanopore single cell long read data using 10X RNA-seq kit. use splice annotation in alignment.

global_parameters

	has_UMI : True

	generate_raw_isoform : False

isoform_parameters

	Min_sup_pct : 0.2

	MAX_SPLICE_MATCH_DIST : 10

	random_seed : 666666

	Min_cnt_pct : 0.001

	MAX_DIST : 10

	Min_sup_cnt : 5

	MAX_TS_DIST : 120

	Max_site_per_splice : 3

	strand_specific : -1

	remove_incomp_reads : 4

	min_fl_exon_len : 40

pipeline_parameters

	do_transcript_quantification : True

	do_read_realignment : True

	do_genome_alignment : True

	do_isoform_identification : True

transcript_counting

	min_tr_coverage : 0.4

	min_read_coverage : 0.4

realign_parameters

	use_annotation : True

alignment_parameters

	no_flank : False

	use_junctions : True

output directory not exist, create one:

FLAMES_Output/test

Input parameters:

	gene annotation: hg38v99.Cellranger.genes.gtf

	genome fasta: hg38v99.Cellranger.genome.fa

	input fastq: test.demultiplexed.fq.gz

	output directory: FLAMES_Output/test

	directory contains minimap2: /Software/anaconda_py2/bin/

### align reads to genome using minimap2 2021-01-30 12:48:05



Traceback (most recent call last):

  File "/FLAMES/python/sc_long_pipeline.py", line 213, in <module>

    sc_long_pipeline(args)

  File "/FLAMES/python/sc_long_pipeline.py", line 159, in sc_long_pipeline

    minimap2_align(args.minimap2_dir, args.genomefa, args.infq, tmp_bam, no_flank=config_dict["alignment_parameters"]["no_flank"], bed12_junc=tmp_bed if config_dict["alignment_parameters"]["use_junctions"] else None)

  File "/FLAMES/python/minimap2_align.py", line 37, in minimap2_align

    print subprocess.check_output([align_cmd], shell=True, stderr=subprocess.STDOUT)

  File "/Software/anaconda_py2/lib/python2.7/subprocess.py", line 223, in check_output

    raise CalledProcessError(retcode, cmd, output=output)

subprocess.CalledProcessError: Command '['/Software/anaconda_py2/bin/minimap2 -ax splice -t 12 --junc-bed FLAMES_Output/test/tmp.splice_anno.bed12 --junc-bonus 1  -k14 --secondary=no hg38v99.Cellranger.genome.fa test.demultiplexed.fq.gz | samtools view -bS -@ 4 -m 2G -o FLAMES_Output/test/tmp.align.bam -  ']' returned non-zero exit status 1
```

**Comment by ChangqingW** [comment]
could you run
```
/Software/anaconda_py2/bin/minimap2 -ax splice -t 12 --junc-bed FLAMES_Output/test/tmp.splice_anno.bed12 --junc-bonus 1  -k14 --secondary=no hg38v99.Cellranger.genome.fa test.demultiplexed.fq.gz | samtools view -bS -@ 4 -m 2G -o FLAMES_Output/test/tmp.align.bam -
```
and see if minimap2 / samtools print any error message?
