### ISSUE TITLE
sc_long_pipeline.py--> ValueError: invalid contig `chr1`

### ISSUE THREAD

**Issue by jeneaadams** [LuyiTian/FLAMES#37]
Hi, both my ```genome.fa``` and ```gff3``` files use contig ```chr1```. Is there support for this format or parameters I can set to solve this error? 

>Traceback (most recent call last):
  File "PATH/TO/FLAMES/python/sc_long_pipeline.py", line 240, in <module>
    sc_long_pipeline(args)
  File "PATH/TO/FLAMES/python/sc_long_pipeline.py", line 193, in sc_long_pipeline
    raw_gff3=raw_splice_isoform if config_dict["global_parameters"]["generate_raw_isoform"] else None)
  File "PATH/TO/FLAMES/python/sc_longread.py", line 1123, in group_bam2isoform
    it_region = bamfile.fetch(ch, bl.s, bl.e)
  File "pysam/libcalignmentfile.pyx", line 1081, in pysam.libcalignmentfile.AlignmentFile.fetch
  File "pysam/libchtslib.pyx", line 686, in pysam.libchtslib.HTSFile.parse_region
ValueError: invalid contig `chr1

**Comment by LuyiTian** [comment]
Oh I think  it is a pysam error which happens when reading the bam file. It is likely that your bam file is generated with a different reference without chr1 or there is no chr1 reads in your bam files so it give this error. you can check your bam file header using `samtools view -H $your_bam_file`.

**Comment by jeneaadams** [comment]
Hello, 

Here's the structure of our input fastq from the ``match_cell_barcode`` step: 
<img width="1030" alt="image" src="https://user-images.githubusercontent.com/54278292/213558215-6508c8a1-5162-4923-9399-b684335e10d9.png">


Here's the BAM file the full pipeline starts to output: 
<img width="1030" alt="image" src="https://user-images.githubusercontent.com/54278292/213557921-5426ff1c-6a64-4dbb-a9b4-a8aafd77fafd.png">

The transcript ID replaced the chromosome ID in the name file, and there's no chromosome contig. Also there's no read name, just a cell barcode as a read name in the bam file. 

Usage for ``sc_long_pipeline.py``: 
``
~/FLAMES/python/sc_long_pipeline.py --gff3 ~/gencode.v39.annotation.gff3 --infq ~/MYL6-out_fastq.gz --outdir ~/flames_test_MYL6/ --genomefa ~/gencode.v39.transcripts.fa --minimap2_dir ~/anaconda3/envs/FLAMES3/bin/
``

**Comment by jeneaadams** [comment]
Hello, 

Here's the structure of our input fastq from the ``match_cell_barcode`` step: 
<img width="1030" alt="image" src="https://user-images.githubusercontent.com/54278292/213558215-6508c8a1-5162-4923-9399-b684335e10d9.png">


Here's the BAM file the full pipeline starts to output: 
<img width="1030" alt="image" src="https://user-images.githubusercontent.com/54278292/213557921-5426ff1c-6a64-4dbb-a9b4-a8aafd77fafd.png">

The transcript ID replaced the chromosome ID in the name file, and there's no chromosome contig. Also there's no read name, just a cell barcode as a read name in the bam file. 

Usage for ``sc_long_pipeline.py``: 
``
~/FLAMES/python/sc_long_pipeline.py --gff3 ~/gencode.v39.annotation.gff3 --infq ~/out_pcr5_hq_fastq.gz --outdir ~/flames_test_MYL6/ --genomefa ~/gencode.v39.transcripts.fa --minimap2_dir ~/anaconda3/envs/FLAMES3/bin/
``

**Comment by LuyiTian** [comment]
The genomefa should be the fasta file of genome instead of transcript. For human the most recent primary assembly should be: https://ftp.ebi.ac.uk/pub/databases/gencode/Gencode_human/release_42/GRCh38.primary_assembly.genome.fa.gz. other versions have similar naming convention.  

The FLAMES software will generate the transcript fasta file, which contains the known transcript and the new transcript called from the bam file.

**Comment by jeneaadams** [comment]
I see, thanks. With the updated input, I get a new error:

> Traceback (most recent call last):
>   File "~FLAMES_analysis/FLAMES/python/count_tr.py", line 159, in parse_realigned_bam
>     bc, umi = r.split("#")[0].split("_")  # assume cleaned barcode
> ValueError: not enough values to unpack (expected 2, got 1)
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "~FLAMES/python/sc_long_pipeline.py", line 240, in <module>
>     sc_long_pipeline(args)
>   File "~FLAMES/python/sc_long_pipeline.py", line 225, in sc_long_pipeline
>     realign_bam, transcript_fa_idx, config_dict["isoform_parameters"]["Min_sup_cnt"], config_dict["transcript_counting"]["min_tr_coverage"], config_dict["transcript_counting"]["min_read_coverage"])
>   File "~FLAMES/python/count_tr.py", line 163, in parse_realigned_bam
>     "Please check if barcode and UMI are delimited by \"_\"")
> ValueError: Please check if barcode and UMI are delimited by "_"
> 

The fastq I provided for ``--infq`` is the binary fastq file from the first barcode matching step. Can you also confirm this should be a binary file generated from ``match_cell_barcode``?

**Comment by ChangqingW** [comment]
Yes, it is expecting fastq files outputted by match_cell_barcode, where the identifier field has the format of `@[barcode]_[umi]#[original id]`

**Comment by dontwantcode** [comment]
But this fastq file couldn't be viewed by `less`, it's a biniary file. And it couldn't be aligned with `minimap2` either, here is the error log:
```
Input parameters:
        gene annotation: /home/reference/annotation/human/gencode.v39.annotation.gff3
        genome fasta: /home/reference/refdata-gex-GRCh38-2020-A/fasta/genome.fa
        input fastq: /home/FLAMES/out.fastq
        output directory: /home/FLAMES/
        directory contains minimap2: /home/software/minimap2-2.24_x64-linux/
### align reads to genome using minimap2 2023-02-03 11:25:22
b''
Traceback (most recent call last):
  File "./python/sc_long_pipeline.py", line 240, in <module>
    sc_long_pipeline(args)
  File "./python/sc_long_pipeline.py", line 168, in sc_long_pipeline
    seed=config_dict["alignment_parameters"]["seed"])
  File "/home/software/FLAMES/python/minimap2_align.py", line 41, in minimap2_align
    shell=True, stderr=subprocess.STDOUT))
  File "/home/software/anaconda3/envs/py3.7/lib/python3.7/subprocess.py", line 411, in check_output
    **kwargs).stdout
  File "/home/software/anaconda3/envs/py3.7/lib/python3.7/subprocess.py", line 512, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['/home/software/minimap2-2.24_x64-linux/minimap2 -ax splice -t 12 --junc-bed /home/FLAMES/tmp.splice_anno.bed12 --junc-bonus 1  -k14 --secondary=no --seed 2022 /home/reference/refdata-gex-GRCh38-2020-A/fasta/genome.fa /home/FLAMES//out.fastq | samtools view -bS -@ 4 -m 2G -o /home/FLAMES/tmp.alig
n.bam -  ']' returned non-zero exit status 1.
```
Here is the output statistic for `match_cell_barcode`, which may help:
```
###total read: 26292
###barcode hm match: 13191
###barcode fuzzy match: 2127
###barcode not match: 10974
###too short: 0
```

**Comment by LuyiTian** [comment]
@dontwantcode  there seem to be an extra `/` in the minimap code: `/home/FLAMES//out.fastq`

```
subprocess.CalledProcessError: Command '['/home/software/minimap2-2.24_x64-linux/minimap2 -ax splice -t 12 --junc-bed /home/FLAMES/tmp.splice_anno.bed12 --junc-bonus 1  -k14 --secondary=no --seed 2022 /home/reference/refdata-gex-GRCh38-2020-A/fasta/genome.fa /home/FLAMES//out.fastq | samtools view -bS -@ 4 -m 2G -o /home/FLAMES/tmp.alig
n.bam -  ']'
```

**Comment by dontwantcode** [comment]
Hi Luyi,
I don't think it should be the problem of `\\`, which is equivalent as `\` in linux path.
Here is a verification:
```
Input parameters:
        gene annotation: /home/reference/annotation/human/gencode.v39.annotation.gff3
        genome fasta: /home/reference/refdata-gex-GRCh38-2020-A/fasta/genome.fa
        input fastq: /home/FLAMES/out.fastq
        output directory: /home/FLAMES
        directory contains minimap2: /home/software/minimap2-2.24_x64-linux/
### align reads to genome using minimap2 2023-02-11 22:09:24
b''
Traceback (most recent call last):
  File "./python/sc_long_pipeline.py", line 240, in <module>
    sc_long_pipeline(args)
  File "./python/sc_long_pipeline.py", line 168, in sc_long_pipeline
    seed=config_dict["alignment_parameters"]["seed"])
  File "/home/software/FLAMES/python/minimap2_align.py", line 41, in minimap2_align
    shell=True, stderr=subprocess.STDOUT))
  File "/home/software/anaconda3/envs/py3.7/lib/python3.7/subprocess.py", line 411, in check_output
    **kwargs).stdout
  File "/home/software/anaconda3/envs/py3.7/lib/python3.7/subprocess.py", line 512, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['/home/software/minimap2-2.24_x64-linux/minimap2 -ax splice -t 12 --junc-bed /home/FLAMES/tmp.splice_anno.bed12 --junc-bonus 1  -k14 --secondary=no --seed 2022 /home/reference/refdata-gex-GRCh38-2020-A/fasta/genome.fa /home/FLAMES/out.fastq | samtools view -bS -@ 4 -m 2G -o /home/FLAMES/tmp.align
.bam -  ']' returned non-zero exit status 1.
```

**Comment by ChangqingW** [comment]
> But this fastq file couldn't be viewed by `less`, it's a biniary file. And it couldn't be aligned with `minimap2` either, here is the error log:
> 
> ```
> Input parameters:
>         gene annotation: /home/reference/annotation/human/gencode.v39.annotation.gff3
>         genome fasta: /home/reference/refdata-gex-GRCh38-2020-A/fasta/genome.fa
>         input fastq: /home/FLAMES/out.fastq
>         output directory: /home/FLAMES/
>         directory contains minimap2: /home/software/minimap2-2.24_x64-linux/
> ### align reads to genome using minimap2 2023-02-03 11:25:22
> b''
> Traceback (most recent call last):
>   File "./python/sc_long_pipeline.py", line 240, in <module>
>     sc_long_pipeline(args)
>   File "./python/sc_long_pipeline.py", line 168, in sc_long_pipeline
>     seed=config_dict["alignment_parameters"]["seed"])
>   File "/home/software/FLAMES/python/minimap2_align.py", line 41, in minimap2_align
>     shell=True, stderr=subprocess.STDOUT))
>   File "/home/software/anaconda3/envs/py3.7/lib/python3.7/subprocess.py", line 411, in check_output
>     **kwargs).stdout
>   File "/home/software/anaconda3/envs/py3.7/lib/python3.7/subprocess.py", line 512, in run
>     output=stdout, stderr=stderr)
> subprocess.CalledProcessError: Command '['/home/software/minimap2-2.24_x64-linux/minimap2 -ax splice -t 12 --junc-bed /home/FLAMES/tmp.splice_anno.bed12 --junc-bonus 1  -k14 --secondary=no --seed 2022 /home/reference/refdata-gex-GRCh38-2020-A/fasta/genome.fa /home/FLAMES//out.fastq | samtools view -bS -@ 4 -m 2G -o /home/FLAMES/tmp.alig
> n.bam -  ']' returned non-zero exit status 1.
> ```
> 
> Here is the output statistic for `match_cell_barcode`, which may help:
> 
> ```
> ###total read: 26292
> ###barcode hm match: 13191
> ###barcode fuzzy match: 2127
> ###barcode not match: 10974
> ###too short: 0
> ```

Should be a gzipped fastq, could you check with zcat? Or maybe post the first line of `xxd out.fastq`
