### ISSUE TITLE
versions for conda dependencies

### ISSUE THREAD

**Issue by nick-youngblut** [LuyiTian/FLAMES#49]
The [README](https://github.com/LuyiTian/FLAMES/blob/master/README.md) states:

```
conda create -n FLAMES \
    "python>=3.7" samtools pysam minimap2 numpy editdistance \
    -c bioconda -c conda-forge
git clone https://github.com/LuyiTian/FLAMES.git
```

What are the supported versions for each of the listed conda dependencies?

**Comment by maxim-h** [comment]
Second that question. The way the environment got resolved causes an error in the pipeline

<details><summary>FLAMES error</summary>

```sh
### generate transcript count matrix 2024-06-24 15:21:21
Traceback (most recent call last):
  File "[prefix]/FLAMES/python/sc_long_pipeline.py", line 240, in
 <module>
    sc_long_pipeline(args)
  File "[prefix]//FLAMES/python/sc_long_pipeline.py", line 224, in
 sc_long_pipeline
    bc_tr_count_dict, bc_tr_badcov_count_dict, tr_kept = parse_realigned_bam(
  File "[prefix]//FLAMES/python/count_tr.py", line 126, in parse_r
ealigned_bam
    rec.query_alignment_length)/rec.infer_read_length(), rec.mapping_quality))
AttributeError: 'pysam.calignedsegment.AlignedSegment' object has no attribute
'infer_read_length'
```

</details>

Here is how the environment looks looks for me.

<details><sumamry>Micromamba list</summary>

```sh
$ micromamba list
List of packages in environment: "[HOME]/.micromamba/envs/FLAMES"

  Name                                  Version       Build                Channel
────────────────────────────────────────────────────────────────────────────────────────
  _libgcc_mutex                         0.1           conda_forge          conda-forge
  _openmp_mutex                         4.5           2_gnu                conda-forge
  _sysroot_linux-64_curr_repodata_hack  3             h69a702a_14          conda-forge
  bcftools                              1.3.1         h5bf99c6_7           bioconda
  bzip2                                 1.0.8         hd590300_5           conda-forge
  c-ares                                1.11.0        h470a237_1           bioconda
  ca-certificates                       2024.6.2      hbcca054_0           conda-forge
  curl                                  7.71.1        he644dc0_8           conda-forge
  editdistance                          0.6.2         py38h17151c0_2       conda-forge
  htslib                                1.3.1         h18ffd7a_3           bioconda
  k8                                    1.2           h6618dc6_1           bioconda
  kernel-headers_linux-64               3.10.0        h4a8ded7_14          conda-forge
  krb5                                  1.17.2        h926e7f8_0           conda-forge
  ld_impl_linux-64                      2.40          hf3520f5_7           conda-forge
  libblas                               3.9.0         22_linux64_openblas  conda-forge
  libcblas                              3.9.0         22_linux64_openblas  conda-forge
  libcurl                               7.71.1        hcdd3856_8           conda-forge
  libedit                               3.1.20191231  he28a2e2_2           conda-forge
  libev                                 4.33          hd590300_2           conda-forge
  libffi                                3.4.2         h7f98852_5           conda-forge
  libgcc-ng                             13.2.0        h77fa898_10          conda-forge
  libgfortran-ng                        13.2.0        h69a702a_10          conda-forge
  libgfortran5                          13.2.0        h3d2ce59_10          conda-forge
  libgomp                               13.2.0        h77fa898_10          conda-forge
  liblapack                             3.9.0         22_linux64_openblas  conda-forge
  libnghttp2                            1.41.0        hab1572f_1           conda-forge
  libnsl                                2.0.1         hd590300_0           conda-forge
  libopenblas                           0.3.27        pthreads_h413a1c8_0  conda-forge
  libsqlite                             3.46.0        hde9e2c9_0           conda-forge
  libssh2                               1.10.0        haa6b8db_3           conda-forge
  libstdcxx-ng                          13.2.0        hc0a3c3a_10          conda-forge
  libuuid                               2.38.1        h0b41bf4_0           conda-forge
  libzlib                               1.2.13        h4ab18f5_6           conda-forge
  minimap2                              2.28          he4a0461_1           bioconda
  ncurses                               6.5           h59595ed_0           conda-forge
  numpy                                 1.24.4        py38h59b608b_0       conda-forge
  openssl                               1.1.1w        hd590300_0           conda-forge
  pip                                   24.0          pyhd8ed1ab_0         conda-forge
  pysam                                 0.9.1         py38hd1a2d5f_10      bioconda
  python                                3.8.15        h257c98d_0_cpython   conda-forge
  python_abi                            3.8           4_cp38               conda-forge
  readline                              8.2           h8228510_1           conda-forge
  samtools                              1.3.1         h80b0bb3_7           bioconda
  setuptools                            70.0.0        pyhd8ed1ab_0         conda-forge
  sysroot_linux-64                      2.17          h4a8ded7_14          conda-forge
  tk                                    8.6.13        noxft_h4845f30_101   conda-forge
  wheel                                 0.43.0        pyhd8ed1ab_1         conda-forge
  xz                                    5.2.6         h166bdaf_0           conda-forge
  zlib                                  1.2.13        h4ab18f5_6           conda-forge
```

</details>


Some googling led me to [this](https://github.com/mroosmalen/nanosv/issues/31) and [this](https://github.com/mroosmalen/nanosv/issues/24) issues which led to the `pysam` [release notes](https://pysam.readthedocs.io/en/latest/release.html#release-0-11-0).

In the end creating a new environment with the following command solved the problem:

```sh
micromamba create -n FLAMES2 \
    "python>=3.7" samtools "pysam>=0.11.0" minimap2 numpy editdistance \
    -c bioconda -c conda-forge
```

Would be nice if dependencies were defined a little more clearly.

**Comment by Aravind-sunda** [comment]
Are there any other minimum versions required that should be specified in the yaml file?
